#!/bin/bash
# Usage: _lcp_make_cmd [Debug|Release]
# Default: Debug

BUILD_TYPE=${1:-Debug}
# BUILD_TYPE=${1:-Release}

BUILD_DIR="_arm_linux_build/${BUILD_TYPE}"

INSTALL_DIR="/nfs/jgkim12/sample/skeleton"

cmake -H. -B"${BUILD_DIR}" \
    -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
    -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DUSE_ARM_TOOLCHAIN=ON \
    -DCMAKE_TOOLCHAIN_FILE=arm_s5pv210-linaro.cmake \
    -G "Unix Makefiles"
    
    # -DBUILD_EXAMPLES=ON \
    # -DBUILD_TESTS=ON \
    # -DBUILD_AUTO_ADD=ON \
    # -DENTRY_EXCLUDE_SRC_COMMON_FOR_TEST_RA=ON
    # -DCMAKE_TOOLCHAIN_FILE=arm_none_linux_gnuabi.cmake \