#ifndef __MGR_CONTRACT_MGR_HEALTH_H__
#define __MGR_CONTRACT_MGR_HEALTH_H__

#include <stdint.h>

#include "util/mgr_bus/mgr_bus.h"

/// @brief Health state of each manager.
typedef enum app_mgr_health_state_e {
        APP_MGR_HEALTH_UNKNOWN = 0,
        APP_MGR_HEALTH_OK = 1,
        APP_MGR_HEALTH_WARN = 2,
        APP_MGR_HEALTH_DEGRADED = 3,
        APP_MGR_HEALTH_RECOVERING = 4,
        APP_MGR_HEALTH_ERR = 5,
        APP_MGR_HEALTH_SHUTDOWN = 6
} app_mgr_health_state_t;

/// @brief Reason code for health transitions.
typedef enum app_mgr_health_reason_e {
        APP_MGR_HEALTH_REASON_NONE = 0,
        APP_MGR_HEALTH_REASON_TIMEOUT = 1,
        APP_MGR_HEALTH_REASON_IPC_FAIL = 2,
        APP_MGR_HEALTH_REASON_CFG_FAIL = 3,
        APP_MGR_HEALTH_REASON_POLICY_FAIL = 4,
        APP_MGR_HEALTH_REASON_DEP_FAIL = 5,
        APP_MGR_HEALTH_REASON_INTERNAL = 6
} app_mgr_health_reason_t;

/// @brief Severity levels for health reporting.
typedef enum app_mgr_health_severity_e {
        APP_MGR_HEALTH_SEV_INFO = 0,
        APP_MGR_HEALTH_SEV_WARN = 1,
        APP_MGR_HEALTH_SEV_ERROR = 2,
        APP_MGR_HEALTH_SEV_CRITICAL = 3
} app_mgr_health_severity_t;

/// @brief Runtime health report generated by each manager.
typedef struct app_mgr_health_report_s {
        mgr_bus_addr_t addr;
        uint16_t state;
        uint16_t reason;
        uint16_t severity;
        uint16_t reserved;
        int32_t err_code;
        uint32_t retry_count;
        uint64_t ts_ms;
} app_mgr_health_report_t;

/// @brief Health threshold configuration.
typedef struct app_mgr_health_threshold_s {
        uint32_t timeout_ms;
        uint32_t max_retry;
        uint32_t recover_hold_ms;
} app_mgr_health_threshold_t;

/// @brief Health evaluation policy.
typedef struct app_mgr_health_policy_s {
        app_mgr_health_threshold_t th;
        uint32_t bounded_retry;
} app_mgr_health_policy_t;

/// @brief Snapshot of health roll-up for orchestration.
typedef struct app_mgr_health_snapshot_s {
        uint32_t ok_count;
        uint32_t warn_count;
        uint32_t degraded_count;
        uint32_t err_count;
} app_mgr_health_snapshot_t;

extern const char *app_mgr_health_state_to_str(uint16_t st);
extern const char *app_mgr_health_reason_to_str(uint16_t reason);

extern int app_mgr_health_report_init(app_mgr_health_report_t *r, mgr_bus_addr_t addr);
extern int app_mgr_health_report_mark_ok(app_mgr_health_report_t *r, uint64_t now_ms);
extern int app_mgr_health_report_mark_warn(app_mgr_health_report_t *r, uint16_t reason, uint64_t now_ms);
extern int app_mgr_health_report_mark_error(app_mgr_health_report_t *r, uint16_t reason, int32_t err, uint64_t now_ms);
extern int app_mgr_health_report_mark_degraded(app_mgr_health_report_t *r, uint16_t reason, uint64_t now_ms);
extern int app_mgr_health_report_mark_recovering(app_mgr_health_report_t *r, uint64_t now_ms);
extern int app_mgr_health_report_mark_shutdown(app_mgr_health_report_t *r, uint64_t now_ms);

extern int app_mgr_health_is_timeout(const app_mgr_health_report_t *r, uint64_t now_ms, uint32_t timeout_ms);
extern int app_mgr_health_eval_next_state(const app_mgr_health_report_t *r, const app_mgr_health_policy_t *p, uint16_t *out_state);

#endif /* __MGR_CONTRACT_MGR_HEALTH_H__ */