#ifndef _SKELETON_VERSION_H_
#define _SKELETON_VERSION_H_

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define COMPILE_DATE_TIME     ""__DATE__" "__TIME__"\n"

#define SKELETON_SW_ENG_VER_MAJOR 2
#define SKELETON_SW_ENG_VER_MINOR 0
#define SKELETON_SW_ENG_VER_PATCH 0
#define SKELETON_SW_ENG_VER_BUILD 0

#define SKELETON_SW_ENG_VER_PREFIX     "SKELETON SW ENG Ver"
#define SKELETON_SW_ENG_VERSION \
        SKELETON_SW_ENG_VER_PREFIX ": V" \
        STR(SKELETON_SW_ENG_VER_MAJOR) "." \
        STR(SKELETON_SW_ENG_VER_MINOR) "." \
        STR(SKELETON_SW_ENG_VER_PATCH) "." \
        STR(SKELETON_SW_ENG_VER_BUILD) " " \
        COMPILE_DATE_TIME

#endif /* _SKELETON_VERSION_H_ */